spring:
  application:
    name: dynamic-tp-nacos-demo
nacos:
  config:
    server-addr: 127.0.0.1:8848
    type: yaml
    data-ids: dynamic-tp-nacos-demo-dev.yml
    auto-refresh: true
    group: ${spring.application.name}
    namespace: ${spring.profiles.active}
    bootstrap:
      enable: true
      log-enable: true


