spring:
  application:
    name: dynamic-tp
nacos:
  config:
    server-addr: 119.3.171.9:8848
    type: yaml
    data-ids: dynamic-tp-dev.yml
    auto-refresh: true
    group: DEFAULT_GROUP
    bootstrap:
      enable: true
      log-enable: true
